using Xunit;

// Run this assembly's tests serially (no cross-collection parallelism).
//
// Why: under `dotnet test` the xUnit v3 tests execute through the VSTest bridge
// (xunit.runner.visualstudio). When several test collections run in parallel there is a
// lost-wakeup race in the bridge's result-reporting message bus: a hang dump of a stuck run shows
// the test threads have already finished and exited (dead threadpool threads, no locks held), yet
// the run never completes — the main thread blocks in XunitAutoGeneratedEntryPoint.Main on
// Task.GetResult() while MessageBus.ReporterWorker sits idle waiting on its queue. The heavier
// resilience test (which spins up an HttpClientFactory pipeline with background timers) only shifts
// timing enough to trigger it; the deadlock is in the runner, not in product or test code.
//
// Disabling collection parallelism makes runs deterministic. This suite is tiny and fast (~0.3s),
// so serial execution costs nothing. If it ever grows large enough that serial runs hurt, the fix
// is to migrate off the VSTest bridge to xUnit v3's native Microsoft.Testing.Platform runner (which
// would also require swapping the JUnit logger used by CI). See AGENTS.md §12.
[assembly: CollectionBehavior(DisableTestParallelization = true)]