// <auto-generated />
using System;
using GridFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GridFlowDbContext))]
    partial class GridFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GridFlow.Domain.GasFlows.GasFlowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("GasDay")
                        .HasColumnType("date");

                    b.Property<long>("KWhFromBiogas")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhFromNorthSea")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhFromTyra")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhToDenmark")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhToOrFromGermany")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhToOrFromStorage")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhToPoland")
                        .HasColumnType("bigint");

                    b.Property<long>("KWhToSweden")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Dataset", "GasDay")
                        .IsUnique();

                    b.ToTable("GasFlowRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
